stages:
  - build
  - release

variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE:master
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - test "x$(uname -s)" == "xDarwin" && ! docker foo > /dev/null 2>&1 && eval $(docker-machine env default)
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:image:
  stage: build
  only:
    - master
  tags:
    - shell-executor
    - docker
  script:
    - docker build -t $BUILD_IMAGE mautic-build
    - docker push $BUILD_IMAGE

release:image:
  stage: release
  only: 
    - master
  tags:
    - shell-executor
    - docker
  script:
    - docker pull $BUILD_IMAGE
    - docker tag $BUILD_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE

